name: SuperPermsTest

author: Evenprime

main: cc.co.evenprime.bukkit.superpermstest.SuperPermsTest
version: 0.2

commands:
  superpermstest:
    description: PerformanceTest command
    usage: |
           /<command> playername [samplesize] - run the test

permissions:
  layer11:
    description: Test 1 parent
    default: false
    children:
      layer21:
        description: Test 1 child
        children:
          layer31:
            description: Test 1 grandchild
            children:
              layer41:
                description: Test 1 grandgrandchild
  layer12:
    description: Test 2 parent - The player has this permission assigned
    default: false
    children:
      layer22:
        description: Test 2 child - The player has this permission assigned
        children:
          layer32:
            description: Test 2 grandchild - The player has this permission assigned
            children:
              layer42:
                description: Test 2 grandgrandchild - The player has this permission assigned
  layer13:
    description: Test 3 parent - The player has this permission assigned
    default: false
    children:
      layer23:
        description: Test 3 child
        children:
          layer33:
            description: Test 3 grandchild
            children:
              layer43:
                description: Test 3 grandgrandchild
  layer14:
    description: Test 4 parent
    default: false
    children:
      layer24:
        description: Test 4 child - The player has this permission assigned
        children:
          layer34:
            description: Test 4 grandchild
            children:
              layer44:
                description: Test 4 grandgrandchild
  layer15:
    description: Test 5 parent
    default: false
    children:
      layer25:
        description: Test 5 child
        children:
          layer35:
            description: Test 5 grandchild - The player has this permission assigned
            children:
              layer45:
                description: Test 5 grandgrandchild
  layer16:
    description: Test 6 parent
    default: false
    children:
      layer26:
        description: Test 6 child
        children:
          layer36:
            description: Test 6 grandchild
            children:
              layer46:
                description: Test 6 grandgrandchild - The player has this permission assigned
  layer17:
    description: Test 7 parent - The player has this permission assigned
    default: false
    children:
      layer27:
        description: Test 7 child - The player has this permission assigned as false
        children:
          layer37:
            description: Test 7 grandchild
            children:
              layer47:
                description: Test 7 grandgrandchild
  layer18:
    description: Test 8 parent - The player has this permission assigned
    default: false
    children:
      layer28:
        description: Test 8 child - The player has this permission assigned as false
        children:
          layer38:
            description: Test 8 grandchild - The player has this permission assigned
            children:
              layer48:
                description: Test 8 grandgrandchild

  single1:
    description: Test 9 standalone permission 1
    default: true

  single2:
    description: Test 9 standalone permission 2
    default: false

  str1:
    description: Test 10 parent - The player has this permission assigned
    default: false
    children:
      str1.c1:
        description: Test 10 child

  str1.c2:
    description: Test 10 fake child
    default: false

  str2:
    description: Test 11 standalone
    default: false

  str2.*:
    description: Test 11 parent - The player has this permission assigned
    default: false
    children:
      str2.c1:
        description: Test 11 child

  str2.c2:
    description: Test 11 fake child
    default: false
    
  
  str3.*:
    description: Test 12 standalone - The player has this permission assigned
    default: false
    
  str3:
    description: Test 12 parent
    default: false
    children:
      c1.str3:
        description: Test 12 child
